apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: DEPLOYMENT
  template:
    metadata:
      labels:
        app: DEPLOYMENT
    spec:
      containers:
        - name: app
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always
