apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: payment-deployment
  template:
    metadata:
      labels:
        app: payment-deployment
    spec:
      containers:
        - name: app
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always
