apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: account-deployment
  template:
    metadata:
      labels:
        app: account-deployment
    spec:
      containers:
        - name: app
          image: gcr.io/turing-variety-317113/account-image:1.0.0
          imagePullPolicy: Always
