name: Docker Publish Keycloak

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: keycloak-test


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
 #     - name: Log into registry ${{ env.REGISTRY }}
  #      if: github.event_name != 'pull_request'
   #     uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
    #    with:
     #     registry: ${{ env.REGISTRY }}
      #    username: ${{ github.actor }}
       #   password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Docker build
        run: |-
          docker build -f AccountService/Dockerfile \
          --tag docker.io/dnickel/keycloak-test:1.0.0 \
          --build-arg KEYCLOAK=jboss/keycloak \
          --build-arg KEYCLOAK_VERSION=14.0.0 \
          --build-arg POSTGRES_PASSWORD=${{ secrets.GCP_POSTGRES_PASSWORD }} \
          --build-arg KEYCLOAK_PASSWORD=${{ secrets.KEYCLOAK_PASSWORD }} \
          .
      - name: Login to Docker Hub
        run: |-
          docker login -u dnickel -p Twoiback24
          
      - name: Docker Push
        run: |-
          docker push docker.io/dnickel/keycloak-test:1.0.0
          
      - name: Create network
        run: docker network create keycloak-network
      
      - name: start postgres
        run: |-
          docker run -d --name postgres --net keycloak-network -e POSTGRES_DB=keycloak -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=database postgres
          
      - name: Docker run
        run: |-
          docker run -p 8080:8080 --net keycloak-network -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin docker.io/dnickel/docker-test-image:1.0.0
          
        #  docker run --name keycloak --net keycloak-network jboss/keycloak -e DB_USER=keycloak -e DB_PASSWORD=passwor

